version: '3.8'

services:
  # Frontend React application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: onprem-techprimer-frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - ENVIRONMENT=production
    volumes:
      # Mount SSL certificates for persistence (optional)
      - ssl-certs:/etc/nginx/ssl
      # Mount logs for debugging
      - nginx-logs:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  # Development service (optional)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: onprem-techprimer-frontend-dev
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
      - ENVIRONMENT=dev
    volumes:
      - nginx-logs:/var/log/nginx
    restart: unless-stopped
    profiles:
      - dev
    networks:
      - app-network

volumes:
  ssl-certs:
    driver: local
  nginx-logs:
    driver: local

networks:
  app-network:
    driver: bridge
